on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the release"
        required: true

name: Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: Create local repository directory
        id: local_repo
        run: echo ::set-output name=dir::"$(mktemp -d repo.XXXXXXXX)"
      - name: Package Chart
        run: helm package charts/test && mv *.tgz ${{ steps.local_repo.outputs.dir }}/
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ${{ steps.local_repo.outputs.dir }}/*
          tag: ${{ github.event.inputs.version }}
          overwrite: true
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Release to GitHub
        run: |
          git checkout gh-pages
          echo "test ${{ github.event.inputs.version }}" >> index.html

